spring:
  application:
    name: base
  datasource:
    url: jdbc:postgresql://localhost:5432/db-api-base
    username: macbook
    password: "#devmf19"
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

api:
  security:
    default-user: admin
    default-password: password
    secret: ${JWT_SECRET:secret}
    expirationInMs: ${JWT_EXPIRATION_IN_MS:20000000}

logging:
  level:
    root: info
    com:
      devmf:
        base: debug
    org:
      springdoc: error
  pattern:
    console: "%highlight(%-5level) %d{'yy-MM-dd HH:mm:ss'} - file %F, method %M, line %L: %replace(%msg){'\n',''}%n%ex{full}"
    #IDEBUG 25-04-26 17:54:34 - file AuthController.java, method create, line 27: com.devmf.base.common.model.Request@54fe7f1d

